# Generated by Django 2.2.7 on 2019-11-15 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voucher',
            name='usage',
        ),
        migrations.AddField(
            model_name='voucher',
            name='usage_limit',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='voucher',
            name='usage_no',
            field=models.IntegerField(default=0),
        ),
    ]
