# Generated by Django 2.2.7 on 2019-11-19 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0003_auto_20191115_1439'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voucher',
            old_name='code',
            new_name='code_field',
        ),
        migrations.RenameField(
            model_name='voucher',
            old_name='discount',
            new_name='discount_field',
        ),
        migrations.RenameField(
            model_name='voucher',
            old_name='usage_limit',
            new_name='usage_limit_field',
        ),
        migrations.RenameField(
            model_name='voucher',
            old_name='usage_no',
            new_name='usage_no_field',
        ),
    ]
